AWSTemplateFormatVersion: '2010-09-09'
Description: 'MeCab Lambda Layer for Japanese Text Processing'

Resources:
  MeCabLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: mecab-layer
      Description: 'MeCab library for Japanese morphological analysis'
      Content:
        S3Bucket: !Ref LayerBucket
        S3Key: mecab-layer.zip
      CompatibleRuntimes:
        - python3.11
        - python3.9
      CompatibleArchitectures:
        - x86_64
        - arm64

  LayerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-mecab-layer-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  MeCabLayerArn:
    Description: 'ARN of the MeCab Lambda Layer'
    Value: !Ref MeCabLayer
    Export:
      Name: !Sub '${AWS::StackName}-MeCabLayerArn'
